---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: satellite
  name: satellite-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: satellite-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: satellite-app
    spec:
      containers:
      - image: kanishka2019758/satellite2019758:main
        imagePullPolicy: Always
        name: satellite-app
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: satellite
  name: satellite-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: satellite-app
  type: LoadBalancer
status:
  loadBalancer: {}