server:
  port: 8088

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://satellite.c5zpdwkp3drl.ap-southeast-1.rds.amazonaws.com:3306/satellite_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true